apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-booking-app
  namespace: hotel-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-booking
  template:
    metadata:
      labels:
        app: hotel-booking
    spec:
      containers:
      - name: app
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/hotel-booking:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: hotel-booking-config
        - secretRef:
            name: hotel-booking-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20 