version: '3.8'

services:
  frontend:
    build: .
    container_name: booking-frontend
    ports:
      - "3000:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - booking-network

networks:
  booking-network:
    external: true 